//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace application_query.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_table
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public string email_id { get; set; }
        public string profession { get; set; }
        public Nullable<int> marks_12th { get; set; }
        public string ug_degree { get; set; }
        public string address { get; set; }
        public Nullable<int> mobile_no { get; set; }
        public string courses { get; set; }
    }
}
